//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visits.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class label
    {
        public int id { get; set; }
        public string locale_id { get; set; }
        public string label1 { get; set; }
        public string translation { get; set; }
    
        public virtual locale locale { get; set; }
    }
}
