//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visits.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class locale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public locale()
        {
            this.labels = new HashSet<label>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public string selector_id { get; set; }
        public string selector_name { get; set; }
        public string date_time_format { get; set; }
        public string date_time_format_front_end { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<label> labels { get; set; }
    }
}
