//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visits.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class preregistrations_settings
    {
        public long id { get; set; }
        public short link_expiration_hours { get; set; }
        public string link_url_format { get; set; }
        public string email_subject { get; set; }
        public string email_body_format { get; set; }
        public string email_date_time_format { get; set; }
        public string smtp_host { get; set; }
        public short smtp_port { get; set; }
        public string smtp_user { get; set; }
        public string smtp_password { get; set; }
    }
}
