//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visits.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class preregistration
    {
        public byte[] guid { get; set; }
        public string company_key { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public System.DateTime visit_date { get; set; }
        public string motive { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> confirmed_at { get; set; }
    }
}
