//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visits.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class visitsEntities : DbContext
    {
        public visitsEntities()
            : base("name=visitsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<label> labels { get; set; }
        public virtual DbSet<locale> locales { get; set; }
        public virtual DbSet<preregistration> preregistrations { get; set; }
        public virtual DbSet<preregistrations_settings> preregistrations_settings { get; set; }
    }
}
